[package]
name = "image-viewer"
version = "0.0.3"
publish = false
edition = "2021"
rust-version = "1.70"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
fltk = { version = "1.4.7", features = ["use-wayland", "system-fltk"] }
